### ISSUE TITLE
PyCharm plugin & Pycrunch engine started but nothing append in UI

### ISSUE THREAD

**Issue by sGeeK44** [gleb-sevruk/pycrunch-engine#113]
Hi, first of all, thank's a lot for your wonderfull project :) I'm a fanatic of NCrunch/Wallaby.js and it's a long time that i'm looking for a tools like fot python !
I've tried something long time ago :sweat_smile: (https://github.com/sGeeK44/python-live-testing) but never see light. maybe a day i can contribute to develop VsCode plugin to your project.

I tried to setup tool, but nothing append in my UI (no circle color). When i open web-ui, test is well discorvered but doesnt run automaticly, I have to click on it.

Could you give me some help ?
How can I activate log to view what's coul be my problem ?

![image](https://github.com/gleb-sevruk/pycrunch-engine/assets/8371625/7de14f90-af4b-479f-a050-291564fc3f1f)
![image](https://github.com/gleb-sevruk/pycrunch-engine/assets/8371625/ef3edb17-cfbe-4616-b816-ff65333deebe)

**Comment by gleb-sevruk** [comment]
Hello, the intended behavior is that tests won't be run automatically on engine startup, hence you do not see coverage.

It may be time-consuming to run all at once, but I agree that this is not clear. 

Please try opening PyCrunch tool window in IDE (noted in arrow) and run the desired tests manually for the first time:
<img width="1263" alt="image" src="https://github.com/gleb-sevruk/pycrunch-engine/assets/609801/8f33fd38-1e4d-4342-927d-f661c8f8889d">
Do you see discovered tests there?

You can select all tests by CMD+A (Ctrl+A on Windows)


For logs you will need to change file `log_configuration.yaml` in site-packages: `/Users/gleb/venv/pycrunch_integration_tests_3_11/lib/python3.11/site-packages/pycrunch/log_configuration.yaml`

<img width="1236" alt="image" src="https://github.com/gleb-sevruk/pycrunch-engine/assets/609801/0af2ce49-a8ed-48b2-aaee-8cb7664037cf">
and change 
```
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
```
To `level` to `DEBUG`
```
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
```

By the way, your link (https://github.com/sGeeK44/python-live-testing) is not working, probably repo is private :)


And there is VSCode extension in development now and will be ready for alpha release in week or two, we will open source repository with the extension soon
