### ISSUE TITLE
Issue with existing pytest tests using pytest.mark.django_db annotation

### ISSUE THREAD

**Issue by majorgilles** [gleb-sevruk/pycrunch-engine#126]
Hello, I'm unable to get pycrunch fully runnning with tests that involve django via `@pytest.mark.django_db` decorator.

1. I've had to set `DJANGO_ALLOW_ASYNC_UNSAFE=true` to avoid a first few errors linked to asyncio
2. When running an individual test it seems like the decorator is not properly configured:
<img width="2769" alt="Screenshot 2025-01-06 at 17 35 45" src="https://github.com/user-attachments/assets/2e814d1a-4b48-47d5-9261-6733ee68ecc1" />

This does not happen when running the test normally via pycharm.

Pycrunch config is the following:
```yaml
discovery:
  exclusions:
  - test/e2e/
  - test/integration/
  - node_modules/
engine:
  cpu-cores: 8
  enable-web-ui: false
  load-pytest-plugins: true
  runtime: pytest
  timeout: 900
pinned-tests: []
```

Dependencies are the following:
```toml
[tool.poetry.group.testing.dependencies]
click = "==8.1.8" # used in test/cassettes/s3_sync.py for managing cassettes
coveralls = "==4.0.1"
coverage = "==7.6.1"
freezegun = "==1.5.1"
model-bakery = "==1.20.0"
moto = "==5.0.22"
pandas = "==2.2.3" # necessary to run lizy_predictions related tests
pytest = "==7.4.4"
pytest-asyncio = "==0.23.7"
pytest-cov = "==5.0.0"
pytest-custom-exit-code = "==0.3.0"
pytest-django = "==4.9.0"
pytest-mock = "==3.12.0"
pytest-recording = "==0.13.2"
pytest-socket = "==0.7.0"
pytest-timeout = "==2.3.1"
pytest-xdist = "==3.5.0"
vcrpy = "==4.4.0"

[tool.poetry.group.tdd]
optional = true

[tool.poetry.group.tdd.dependencies]
pycrunch-engine = "==1.6.4"
```
