### ISSUE TITLE
exclusion does not work

### ISSUE THREAD

**Issue by stefaneidelloth** [gleb-sevruk/pycrunch-engine#80]
I tried to adpt .pychrun-config.yaml to exclude some integration test folder for the unit test coverage (see below).

However, the tests in 

back_end/test_integration are still discovered

I tried both, to exclude the whole directory as well as to exclude the individual file. 

I use PyCharm 2022.1.2 (Community Edition)

```
# This configuration file is used by PyCrunch, a PyCharm extension that shows
# pytest coverage in the PyCharm code editor

discovery:
  # some tests should not be considered for the unit test coverage:
  exclusions:
  - back_end/test_integration/
  - back_end/test_integration/calculation/test_calculation.py
engine:
  enable-web-ui: false
  load-pytest-plugins: true
  runtime: pytest
  cpu-cores: 4
pinned-tests: []
```

![image](https://user-images.githubusercontent.com/12675339/209651660-1ddd98f0-4719-4103-a28e-c01fed519a98.png)
